apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qgl68fcwq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qgl68fcwq-go 
  name: qgl68fcwq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qgl68fcwq-go 
